services:
    gnugat_search_engine.build:
        class: Gnugat\SearchEngine\Build

    gnugat_search_engine.criteria_factory:
        class: Gnugat\SearchEngine\CriteriaFactory
        factory: ["@gnugat_search_engine.build", criteriaFactory]

    gnugat_search_engine.identifier_engine:
        class: Gnugat\SearchEngine\IdentifierEngine
        factory: ["@gnugat_search_engine.build", identifierEngine]
        arguments:
            - "@gnugat_search_engine.fetcher"

    gnugat_search_engine.search_engine:
        class: Gnugat\SearchEngine\SearchEngine
        factory: ["@gnugat_search_engine.build", searchEngine]
        arguments:
            - "@gnugat_search_engine.fetcher"
